# docker-compose.yml
services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: "/bin/sh entrypoint.sh"
    volumes:
      - .:/code  

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=mininfo
      - POSTGRES_USER=mininfo
      - POSTGRES_PASSWORD=123456
      - POSTGRES_HOST_AUTH_METHOD=trust
      - ALLOW_IP_RANGE=0.0.0.0/0
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: