# Generated by Django 5.1.6 on 2025-06-05 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'etiqueta',
                'verbose_name_plural': 'etiquetas',
            },
        ),
        migrations.CreateModel(
            name='PalavraChave',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'palavra chave',
                'verbose_name_plural': 'palavras chave',
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('destaque', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('qualificacao', models.CharField(choices=[('A', 'NÃO SEI 1'), ('B', 'não sei mas em minusculo')], max_length=1)),
                ('periodicidade', models.CharField(choices=[('diariamente', 'Diariamente'), ('semanalmente', 'Semanalmente'), ('mensalmente', 'Mensalmente'), ('anualmente', 'Anualmente'), ('bianualmente', 'Bianualmente'), ('a cada 3 anos', 'A cada 3 anos'), ('a cada 5 anos', 'A cada 5 anos')], max_length=20)),
                ('conceito', models.TextField(blank=True, max_length=500)),
                ('metodo_de_calculo', models.TextField(blank=True, max_length=500)),
                ('interpretacao', models.TextField(blank=True, max_length=500)),
                ('atualizado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atualizado_por', to=settings.AUTH_USER_MODEL)),
                ('etiqueta', models.ManyToManyField(to='indicador.etiqueta')),
                ('responsavel_tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsavel_tecnico', to=settings.AUTH_USER_MODEL)),
                ('palavra_chave', models.ManyToManyField(to='indicador.palavrachave')),
            ],
            options={
                'verbose_name': 'indicador',
                'verbose_name_plural': 'indicadores',
            },
        ),
    ]
